grpc:
  server:
    port: 50061
    reflection-service-enabled: true
    max-inbound-message-size: 1GB
    keep-alive-timeout: 30
server:
  port: 8080
#  client:
#    srv2:
#      address: 'static://localhost:50052'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext
#      max-inbound-message-size: 1GB
#      keep-alive-time: 30s
#
#logging:
#  level:
#    root: debug
